package com.meshlink.simulator.core

import com.meshlink.simulator.metrics.NetworkRecorder
import com.meshlink.simulator.node.SimulatedNode
import com.meshlink.simulator.node.SimulatedNode.NodeConfig
import com.meshlink.simulator.profile.NetworkProfile
import com.meshlink.simulator.security.SimulatedSecurityLayer
import com.meshlink.simulator.topology.TopologyBuilder
import com.meshlink.simulator.transport.Link
import com.meshlink.simulator.transport.SimulatedTransport
import com.meshlink.simulator.transport.TransportConfig

/**
 * Kotlin DSL builder for creating [SimulationEnvironment] instances.
 *
 * Provides a concise, readable way to configure simulations for tests.
 *
 * Usage:
 * ```kotlin
 * val sim = MeshSimulator.build {
 *     nodes(5) { idx -> "node-$idx" }  // 5 nodes with custom IDs
 *     topology(TopologyBuilder.ring(nodeIds))
 *     profile(NetworkProfile.HighLoss)
 *     clockSeed(1_000)
 *     randomSeed(42L)
 * }
 * sim.node("node-0").sendPacket("node-4", "hello")
 * sim.step(500)
 * sim.runUntilQuiet()
 * ```
 */
class MeshSimulator private constructor() {

    // ── DSL state ─────────────────────────────────────────────────────────────────

    private var nodeIds: List<String> = emptyList()
    private var linksBuilder: (List<String>) -> List<Link> = { ids -> TopologyBuilder.fullyConnected(ids) }
    private var profile: NetworkProfile = NetworkProfile.PerfectNetwork
    private var nodeConfig: NodeConfig = NodeConfig()
    private var clockStartMs: Long = 0L
    private var randomSeed: Long = 42L

    // ── DSL Methods ───────────────────────────────────────────────────────────────

    /**
     * Adds [count] nodes with auto-generated IDs: `node-0`, `node-1`, …
     */
    fun nodes(count: Int): MeshSimulator {
        nodeIds = (0 until count).map { "node-$it" }
        return this
    }

    /**
     * Adds nodes with IDs generated by [idFactory]. Index is passed to the factory.
     * ```kotlin
     * nodes(5) { idx -> "device-$idx" }
     * ```
     */
    fun nodes(count: Int, idFactory: (Int) -> String): MeshSimulator {
        nodeIds = (0 until count).map(idFactory)
        return this
    }

    /**
     * Uses the provided explicit list of node IDs.
     */
    fun nodes(ids: List<String>): MeshSimulator {
        nodeIds = ids
        return this
    }

    /**
     * Sets the topology by providing a lambda that receives the node ID list
     * and returns a list of [Link]s.
     * ```kotlin
     * topology { ids -> TopologyBuilder.ring(ids) }
     * ```
     */
    fun topology(builder: (List<String>) -> List<Link>): MeshSimulator {
        linksBuilder = builder
        return this
    }

    /**
     * Sets a pre-built list of [Link]s directly.
     */
    fun topology(links: List<Link>): MeshSimulator {
        linksBuilder = { links }
        return this
    }

    /**
     * Applies a [NetworkProfile] to all links in the simulation.
     */
    fun profile(p: NetworkProfile): MeshSimulator {
        profile = p
        return this
    }

    /**
     * Overrides per-node routing configuration (TTL, maxHops, relay, encryption enforcement).
     */
    fun nodeConfig(config: NodeConfig): MeshSimulator {
        nodeConfig = config
        return this
    }

    /**
     * Sets the virtual clock's starting time in milliseconds (default: 0).
     */
    fun clockSeed(startMs: Long): MeshSimulator {
        clockStartMs = startMs
        return this
    }

    /**
     * Sets the random seed for transport decisions (latency sampling, loss).
     */
    fun randomSeed(seed: Long): MeshSimulator {
        randomSeed = seed
        return this
    }

    // ── Build ─────────────────────────────────────────────────────────────────────

    /**
     * Constructs and returns the fully configured [SimulationEnvironment].
     */
    fun build(): SimulationEnvironment {
        require(nodeIds.isNotEmpty()) { "At least one node must be specified via nodes()" }

        val clock = SimulatedClock(clockStartMs)
        val scheduler = SimulationScheduler(clock)
        val recorder = NetworkRecorder()

        val nodes = nodeIds.map { id ->
            val transport = SimulatedTransport(
                nodeId = id,
                clock = clock,
                scheduler = scheduler, // central scheduler
                recorder = recorder,
                seed = randomSeed + id.hashCode()
            )
            SimulatedNode(
                meshId = id,
                clock = clock,
                recorder = recorder,
                transport = transport,
                security = SimulatedSecurityLayer(id, randomSeed),
                configOverride = nodeConfig
            )
        }

        // Apply profile to link configs
        val links = linksBuilder(nodeIds).map { link ->
            link.copy(config = profile.config)
        }

        return SimulationEnvironment.create(nodes, links, clock, scheduler, recorder)
    }

    // ── Companion factory ─────────────────────────────────────────────────────────

    companion object {
        /**
         * Creates a [MeshSimulator] with the provided DSL block and immediately builds it.
         * ```kotlin
         * val sim = MeshSimulator.build {
         *     nodes(10)
         *     topology { ids -> TopologyBuilder.ring(ids) }
         *     profile(NetworkProfile.TypicalBLE)
         * }
         * ```
         */
        fun build(block: MeshSimulator.() -> Unit): SimulationEnvironment =
            MeshSimulator().apply(block).build()

        /**
         * Shortcut to create a simple N-node line topology with PerfectNetwork profile.
         * Useful for quick 2-5 node tests.
         */
        fun line(n: Int, profile: NetworkProfile = NetworkProfile.PerfectNetwork): SimulationEnvironment =
            build {
                nodes(n)
                topology { ids -> TopologyBuilder.line(ids) }
                this.profile(profile)
            }

        /**
         * Shortcut to create a ring topology.
         */
        fun ring(n: Int, profile: NetworkProfile = NetworkProfile.PerfectNetwork): SimulationEnvironment =
            build {
                nodes(n)
                topology { ids -> TopologyBuilder.ring(ids) }
                this.profile(profile)
            }

        /**
         * Shortcut to create a fully connected topology.
         */
        fun mesh(n: Int, profile: NetworkProfile = NetworkProfile.PerfectNetwork): SimulationEnvironment =
            build {
                nodes(n)
                topology { ids -> TopologyBuilder.fullyConnected(ids) }
                this.profile(profile)
            }

        /**
         * Shortcut for a random mesh with configurable density.
         */
        fun random(
            n: Int,
            density: Float = 0.3f,
            seed: Long = 42L,
            profile: NetworkProfile = NetworkProfile.TypicalBLE
        ): SimulationEnvironment = build {
            nodes(n)
            topology { ids -> TopologyBuilder.randomMesh(ids, density, seed) }
            this.profile(profile)
            randomSeed(seed)
        }
    }
}
