org.gradle.jvmargs=-Xmx8192m -XX:+UseG1GC -XX:MaxMetaspaceSize=1024m -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:+TieredCompilation -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx4096m -XX:+UseG1GC -XX:+UseStringDeduplication
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.vfs.watch=true
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.nonFinalResIds=true
kotlin.code.style=official
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
kotlin.daemon.useFallbackCompilerRunner=false
ksp.incremental=false
ksp.incremental.intermodule=false
room.incremental=true
android.lifecycleProcessor.incremental=true
kotlin.incremental.usePreciseJavaTracking=true
ksp.useKsp2=false
kotlin.compiler.execution.strategy=in-process
ksp.strategy=in-process
org.gradle.java.home=/Users/durgaprasadml/.gradle/jdks/jetbrains_s_r_o_-21-aarch64-os_x.2/jbrsdk_jcef-21.0.10-osx-aarch64-b1163.110/Contents/Home


