package com.meshlink.ui.designsystem.theme.colors

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

/**
 * Semantic Color Scheme for Mesh-Link 2026 Design System.
 * Fully supports Light, Dark, and AMOLED theme modes.
 */
@Immutable
data class MeshSemanticColors(
    val primary: Color,
    val secondary: Color,
    val success: Color,
    val warning: Color,
    val danger: Color,
    val mesh: Color,
    val signal: Color,
    val rssi: Color,
    val connected: Color,
    val disconnected: Color,
    val searching: Color,
    val broadcasting: Color,
    val emergency: Color,
    val encrypted: Color,
    val surface: Color,
    val surfaceVariant: Color,
    val elevatedSurface: Color,
    val glassSurface: Color,
    val glassBorder: Color,
    val overlay: Color,
    val background: Color,
    val canvas: Color,
    val cardSurface: Color,
    val border: Color,
    val divider: Color,
    val focus: Color,
    val selection: Color,
    val hover: Color,
    val pressed: Color,
    val disabled: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val outline: Color,
    val ripple: Color,
    val glowAccent: Color,
    // Backward compatibility aliases
    val info: Color = broadcasting,
    val meshConnected: Color = connected,
    val meshSearching: Color = searching,
    val meshOffline: Color = disconnected,
    val signalExcellent: Color = connected,
    val signalMedium: Color = warning,
    val signalWeak: Color = danger,
    val signalStrong: Color = connected,
    val secure: Color = success,
    val online: Color = connected,
    val offline: Color = disconnected,
    val error: Color = danger,
    val primaryBackground: Color = background,
    val secondaryBackground: Color = surfaceVariant,
    val amoledBackground: Color = canvas,
    val onPrimary: Color = Color.White,
    val onSecondary: Color = Color.White,
    val onSurface: Color = textPrimary,
    val onSurfaceVariant: Color = textSecondary,
    val onBackground: Color = textPrimary,
    val onError: Color = Color.White,
    val primaryContainer: Color = surfaceVariant,
    val onPrimaryContainer: Color = textPrimary,
    val secondaryContainer: Color = surfaceVariant,
    val onSecondaryContainer: Color = textPrimary,
    val errorContainer: Color = danger.copy(alpha = 0.2f),
    val onErrorContainer: Color = danger,
    val surfaceContainer: Color = surfaceVariant
)

val LightSemanticColors = MeshSemanticColors(
    primary = Color(0xFF00A86B),
    secondary = Color(0xFF00899B),
    success = MeshColorTokens.SuccessGreenLight,
    warning = Color(0xFFD97706),
    danger = MeshColorTokens.DangerRedLight,
    mesh = Color(0xFF00A86B),
    signal = Color(0xFF00A86B),
    rssi = Color(0xFF00A86B),
    connected = MeshColorTokens.SuccessGreenLight,
    disconnected = MeshColorTokens.MeshDisconnected,
    searching = Color(0xFFD97706),
    broadcasting = Color(0xFF0284C7),
    emergency = MeshColorTokens.EmergencyCrimson,
    encrypted = Color(0xFF0284C7),
    surface = MeshColorTokens.NeutralLightSurface,
    surfaceVariant = Color(0xFFF1F5F9),
    elevatedSurface = MeshColorTokens.NeutralLightElevated,
    glassSurface = MeshColorTokens.GlassSurfaceLight,
    glassBorder = MeshColorTokens.GlassBorderLight,
    overlay = MeshColorTokens.OverlayLight,
    background = MeshColorTokens.NeutralLightBg,
    canvas = MeshColorTokens.NeutralLightCanvas,
    cardSurface = MeshColorTokens.NeutralLightCard,
    border = MeshColorTokens.NeutralLightBorder,
    divider = MeshColorTokens.NeutralLightDivider,
    focus = Color(0xFF00A86B),
    selection = Color(0xFF0284C7),
    hover = MeshColorTokens.HoverLight,
    pressed = MeshColorTokens.PressedLight,
    disabled = MeshColorTokens.DisabledLight,
    textPrimary = MeshColorTokens.NeutralLightTextPrimary,
    textSecondary = MeshColorTokens.NeutralLightTextSecondary,
    textTertiary = MeshColorTokens.NeutralLightTextTertiary,
    outline = MeshColorTokens.NeutralLightOutline,
    ripple = Color(0x1F000000),
    glowAccent = Color(0xFF00A86B)
)

val DarkSemanticColors = MeshSemanticColors(
    primary = MeshColorTokens.CyberMint,
    secondary = MeshColorTokens.QuantumCyan,
    success = MeshColorTokens.SuccessGreen,
    warning = MeshColorTokens.WarningAmber,
    danger = MeshColorTokens.DangerRed,
    mesh = MeshColorTokens.CyberMint,
    signal = MeshColorTokens.CyberMint,
    rssi = MeshColorTokens.CyberMint,
    connected = MeshColorTokens.MeshConnected,
    disconnected = MeshColorTokens.MeshDisconnected,
    searching = MeshColorTokens.MeshSearching,
    broadcasting = MeshColorTokens.MeshBroadcasting,
    emergency = MeshColorTokens.EmergencyCrimson,
    encrypted = MeshColorTokens.MeshEncrypted,
    surface = MeshColorTokens.NeutralDarkSurface,
    surfaceVariant = MeshColorTokens.NeutralDarkElevated,
    elevatedSurface = MeshColorTokens.NeutralDarkElevated,
    glassSurface = MeshColorTokens.GlassSurfaceDark,
    glassBorder = MeshColorTokens.GlassBorderDark,
    overlay = MeshColorTokens.OverlayDark,
    background = MeshColorTokens.NeutralDarkBg,
    canvas = MeshColorTokens.NeutralDarkCanvas,
    cardSurface = MeshColorTokens.NeutralDarkCard,
    border = MeshColorTokens.NeutralDarkBorder,
    divider = MeshColorTokens.NeutralDarkDivider,
    focus = MeshColorTokens.FocusGlow,
    selection = MeshColorTokens.SelectionGlow,
    hover = MeshColorTokens.HoverDark,
    pressed = MeshColorTokens.PressedDark,
    disabled = MeshColorTokens.DisabledDark,
    textPrimary = MeshColorTokens.NeutralDarkTextPrimary,
    textSecondary = MeshColorTokens.NeutralDarkTextSecondary,
    textTertiary = MeshColorTokens.NeutralDarkTextTertiary,
    outline = MeshColorTokens.NeutralDarkOutline,
    ripple = Color(0x3300F59B),
    glowAccent = MeshColorTokens.TacticalTeal
)

val AmoledSemanticColors = MeshSemanticColors(
    primary = MeshColorTokens.CyberMint,
    secondary = MeshColorTokens.QuantumCyan,
    success = MeshColorTokens.SuccessGreen,
    warning = MeshColorTokens.WarningAmber,
    danger = MeshColorTokens.EmergencyCrimson,
    mesh = MeshColorTokens.CyberMint,
    signal = MeshColorTokens.CyberMint,
    rssi = MeshColorTokens.CyberMint,
    connected = MeshColorTokens.MeshConnected,
    disconnected = MeshColorTokens.MeshDisconnected,
    searching = MeshColorTokens.MeshSearching,
    broadcasting = MeshColorTokens.MeshBroadcasting,
    emergency = MeshColorTokens.EmergencyCrimson,
    encrypted = MeshColorTokens.MeshEncrypted,
    surface = MeshColorTokens.AmoledSurface,
    surfaceVariant = MeshColorTokens.AmoledElevated,
    elevatedSurface = MeshColorTokens.AmoledElevated,
    glassSurface = MeshColorTokens.GlassSurfaceAmoled,
    glassBorder = MeshColorTokens.GlassBorderAmoled,
    overlay = Color(0xCC000000),
    background = MeshColorTokens.PitchBlack,
    canvas = MeshColorTokens.PitchBlack,
    cardSurface = MeshColorTokens.AmoledCard,
    border = MeshColorTokens.AmoledBorder,
    divider = MeshColorTokens.AmoledDivider,
    focus = MeshColorTokens.CyberMint,
    selection = MeshColorTokens.QuantumCyan,
    hover = Color(0x1F00F59B),
    pressed = Color(0x3300F59B),
    disabled = Color(0x661E293B),
    textPrimary = Color(0xFFFFFFFF),
    textSecondary = Color(0xFFA1A1AA),
    textTertiary = Color(0xFF71717A),
    outline = MeshColorTokens.AmoledOutline,
    ripple = Color(0x4000F59B),
    glowAccent = MeshColorTokens.CyberMint
)

val LocalMeshSemanticColors = staticCompositionLocalOf { LightSemanticColors }
